name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore LegacyRPG/src/LegacyRPG.sln
    - name: Build
      run: dotnet build LegacyRPG/src/LegacyRPG.sln --no-restore
    - name: Test
      run: dotnet test LegacyRPG/src/LegacyRPG.Test.csproj --no-build --verbosity normal  # Adjust the test project file path
